### ISSUE TITLE
MC - Discord - Setup

### ISSUE THREAD

**Issue by DLmass** [1B0Y/RETRONetwork-Public#41]
Setup category, channels and add reaction roles for easy management and efficiency. Channels which is needed to be created are; announcements, information, rules, general, game for now. The players wouldn't be able to see anything then announcements and information when they have MC Guest as a role. They would have to agree to everything in rules to be able to get the MC Member role. Then MC Member would see the rest of the channels. We would also implement so you need to purchase the role MC Donator which would allow you to be able to write ingame to chat with players there and have different perks ingame (would be possible to add MC Donator with different colors to symbolice what kind of perks you would have ingame and on discord.

**Roles**
RETRO: MC
- MC Guest (placed under RETRO: MC)
- MC Member (placed under RETRO: MC)
- MC Donator (placed under RETRO: MC)
- MC Helper (placed under RETRO: MC)
- MC Moderator (placed under RETRO: MC
- MC Admin (placed under RETRO: MC)
- MC OP (placed under RETRO: MC, DLmass)

**Categories**

- RETRO: MC

**Channels**
- announcements (read only)
- information  (read only)
- rules  (read only)
- general (write, slow mode 2s)
- game (read only for MC Member, write for MC Donator)

**Comment by 1B0Y** [comment]
Construct now completed. Only thing required is Roles bot which is linked to ticket #44

**Comment by 1B0Y** [comment]
Bot now configured and now correctly assigning roles.
Closing.
