### ISSUE TITLE
HUB - Discord - Make #role-select channel + extras

### ISSUE THREAD

**Issue by 1B0Y** [1B0Y/RETRONetwork-Public#48]
As we all understand, @everyone can be annoying.
Time to do a different approach - #role-select under the IMPORTANT category so that players can receive updates from specific servers such as @ HUB, @ Anarchy, @ City, @ MC and @ Urgent

**Comment by mc** [comment]
0 BOY

thats cool. but when you mention individual username, USE THE CORRECT USERNAME.

**Comment by 1B0Y** [comment]
In process of being built, should be done in next 30-60 mins.

**Comment by 1B0Y** [comment]
Done.
